# Generated by Django 4.2.19 on 2025-03-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_list',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
