# Generated by Django 4.2.19 on 2025-03-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Свободно ли'),
        ),
    ]
